# Generated by Django 3.2.13 on 2022-06-29 21:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(model_name='post', name='category',),
        migrations.AddField(model_name='post',name='category', field=models.CharField(choices=[('Dog', 'Dog'),
        ('Puppy', 'Puppy'),
        ('Senior Dog', 'Senior Dog'),
        ('Nature', 'Nature'),
        ('Family', 'Family'),
        ('Big Dog', 'Big Dog'),
        ('Small Dog', 'Small Dog'),
        ('Funny', 'Funny'),
        ('Sleeping', 'Sleeping'),
        ('Playing', 'Playing'),
        ('Zoomies', 'Zoomies'),
        ('Camping', 'Camping'),
        ('Kids & Dogs', 'Kids & Dogs'),
        ('Cute', 'Cute'),
        ('Silly', 'Silly')], default=django.utils.timezone.now, max_length=50),
        preserve_default=False,
    ),
    migrations.DeleteModel(name='Category',),

    ]