# Generated by Django 5.2.2 on 2025-07-07 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('Dog', 'Dog'), ('Puppy', 'Puppy'), ('Senior Dog', 'Senior Dog'), ('Nature', 'Nature'), ('Family', 'Family'), ('Big Dog', 'Big Dog'), ('Small Dog', 'Small Dog'), ('Funny', 'Funny'), ('Sleeping', 'Sleeping'), ('Playing', 'Playing'), ('Zoomies', 'Zoomies'), ('Camping', 'Camping'), ('Kids & Dogs', 'Kids & Dogs'), ('Cute', 'Cute'), ('Silly', 'Silly')], default='Dog', max_length=50),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, default='default_post_umaui6', upload_to=''),
        ),
    ]
