# Generated by Django 5.2.2 on 2025-07-17 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_alter_post_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('Dog', 'Dog'), ('Puppy', 'Puppy'), ('Old Pet', 'Old Pet'), ('Nature', 'Nature'), ('Family', 'Family'), ('Big Pet', 'Big Pet'), ('Small Pet', 'Small Pet'), ('Funny', 'Funny'), ('Sleeping', 'Sleeping'), ('Playing', 'Playing'), ('Zoomies', 'Zoomies'), ('Camping', 'Camping'), ('Kids & Pets', 'Kids & Pets'), ('Cute', 'Cute'), ('Silly', 'Silly')], default='Dog', max_length=50),
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(blank=True, max_length=1000),
        ),
    ]
