# Generated by Django 5.1.3 on 2025-07-20 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_alter_post_category_alter_post_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('Dog', 'Dog'), ('Puppy', 'Puppy'), ('Old Pet', 'Old Pet'), ('Nature', 'Nature'), ('Family', 'Family'), ('Big Pet', 'Big Pet'), ('Small Pet', 'Small Pet'), ('Funny', 'Funny'), ('Sleeping', 'Sleeping'), ('Playing', 'Playing'), ('Zoomies', 'Zoomies'), ('Camping', 'Camping'), ('Kids & Pets', 'Kids & Pets'), ('Cute', 'Cute'), ('Silly', 'Silly')], default='Dog', max_length=51),
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, default='default_post_umaui6', upload_to=''),
        ),
    ]
