# Generated by Django 5.1.3 on 2025-07-20 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_alter_post_category_alter_post_content_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('Dog', 'Dog'), ('Puppy', 'Puppy'), ('Senior Dog', 'Senior Dog'), ('Nature', 'Nature'), ('Family', 'Family'), ('Big Dog', 'Big Dog'), ('Small Dog', 'Small Dog'), ('Funny', 'Funny'), ('Sleeping', 'Sleeping'), ('Playing', 'Playing'), ('Zoomies', 'Zoomies'), ('Camping', 'Camping'), ('Kids & Dogs', 'Kids & Dogs'), ('Cute', 'Cute'), ('Silly', 'Silly')], default='Dog', max_length=51),
        ),
    ]
