# Generated by Django 5.1.3 on 2025-07-20 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_alter_post_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('Dog', 'Dog'), ('Puppy', 'Puppy'), ('Old Pet', 'Old Pet'), ('Nature', 'Nature'), ('Family', 'Family'), ('Big Pet', 'Big Pet'), ('Small Pet', 'Small Pet'), ('Funny', 'Funny'), ('Sleeping', 'Sleeping'), ('Playing', 'Playing'), ('Zoomies', 'Zoomies'), ('Camping', 'Camping'), ('Kids & Pets', 'Kids & Pets'), ('Cute', 'Cute'), ('Silly', 'Silly')], default='Dog', max_length=50),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, default='default_post_wbup9c', upload_to=''),
        ),
    ]
