# Generated by Django 3.2.4 on 2025-09-08 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_rename_content_post_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-created_on']},
        ),
        migrations.RenameField(
            model_name='post',
            old_name='created_at',
            new_name='created_on',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='updated_at',
            new_name='updated_on',
        ),
    ]
