# Generated by Django 3.2.4 on 2025-09-10 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0003_alter_comment_content'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-created_on']},
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='created_at',
            new_name='created_on',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='content',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='updated_at',
            new_name='updated_on',
        ),
    ]
